module: SwiftBeanCountTax
readme: README.md
clean: true
disable_search: true
author: Nef10
author_url: https://github.com/Nef10
root_url: https://Nef10.github.io/SwiftBeanCountTax/
github_url: https://github.com/Nef10/SwiftBeanCountTax
github_file_prefix: https://github.com/Nef10/SwiftBeanCountTax/blob/main
output: ./docs
theme: fullwidth
